# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Network_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_vlan_id', models.IntegerField(default=50)),
                ('subnet_start', models.IntegerField()),
                ('subnet_end', models.IntegerField()),
                ('internal_network_rquired', models.BooleanField(default=False)),
                ('number_of_bridged_internal_networks', models.IntegerField(default=1)),
                ('individual_networks_per_user', models.IntegerField(default=1)),
            ],
        ),
    ]
