# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0002_admin_network_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_network_configuration',
            old_name='individual_networks_per_user',
            new_name='networks_per_user',
        ),
        migrations.RemoveField(
            model_name='admin_network_configuration',
            name='internal_network_rquired',
        ),
        migrations.RemoveField(
            model_name='admin_network_configuration',
            name='number_of_bridged_internal_networks',
        ),
        migrations.AlterField(
            model_name='admin_network_configuration',
            name='course_vlan_id',
            field=models.IntegerField(default=50, unique=True),
        ),
    ]
